version: '3'
services:
  sonar:
    ports:
      - "9000:9000"
    image: sonarqube:latest
    volumes:
      - sonarqube:/opt/sonarqube/
      - openjdk:/opt/java/openjdk/
    networks: 
      - jenkins
    #env_file: env-sonar.txt

  nexus:
    ports:
      - "8081:8081"
    image: sonatype/nexus3:latest
    volumes:
      - sonartype:/opt/sonatype/
      - nexus-data:/nexus-data/
    networks: 
      - jenkins
    #env_file: env-nexus.txt

volumes:
   sonarqube:
   openjdk:
   sonartype:
   nexus-data:

networks:
  jenkins: